name: Build
on:
  workflow_dispatch:  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile
        run: C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
