name: Build
on:
  push:  
  workflow_dispatch:  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile
        run: C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /p:Configuration=Release

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
            name: UltraScaler
            path: "./bin/Release/UltraScaler.exe"
